# Generated by Django 4.2.4 on 2023-09-16 10:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)])),
                ('attack', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)])),
                ('defense', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)])),
                ('special_attack', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)])),
                ('special_defense', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)])),
                ('speed', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)])),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('power', models.IntegerField()),
                ('accuracy', models.IntegerField()),
                ('damage_class', models.CharField(max_length=100)),
                ('pp', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Restriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_modifier', models.FloatField(choices=[(0, '0'), (0.5, '0.5'), (1, '1'), (2, '2')])),
                ('type_defense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_defense', to='api.type')),
                ('type_offense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_offense', to='api.type')),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('base_stats', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.basestat')),
                ('moves', models.ManyToManyField(to='api.move')),
                ('type1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type1', to='api.type')),
                ('type2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type2', to='api.type')),
            ],
        ),
    ]
