# Generated by Django 4.2.4 on 2023-10-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_mediarequest_dbrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbrequest',
            name='request_url',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
